package com.tt.game.utils;

public interface GameConstants {
	String TITLE = "Dragon Ninja";
	String POWERP_TITLE = "DRAGON NINJA";
	String POWERB_TITLE = "KARNOV ( BOSS )";
	String BG_IMG = "DJ_Stage.png";
	String SPLASH_IMG = "splash.png";
	String INSTRUCTION_IMG = "instructions.png";
	String CONTROLS_IMG = "controls.png";
	String HURTP = "accidentally-punching-the-floor-99814.mp3";
	String HURTB = "hurt.mp3";
	String HURTE = "oof-97698.mp3";
	String CLEAR = "Clear.mp3";
	String GAME_OVER = "Game_Over.mp3";
	String SPLASH_MUSIC = "splashmusic.mp3";
	String INGAME_MUSIC = "in_game_music.mp3";
	String HADWOKEN_P = "hadwokenP.mp3";
	String HADWOKEN_B = "hadwokenB.mp3";
	String PLAYER_IMG = "DJ_Player..png";
	String ENEMY_IMG = "DJ_Buki..png";
	String BOSS_IMG = "DJ_Karnov..png";
	int GWIDTH = 1350;
	int GHEIGHT = 660;
	int FLOOR = GHEIGHT - 100;
	int GAME_LOOP = 120;
	int WIN = 100;
	int DEAD = -2;
	int DAMAGE = -1;
	int IDLE = 0;
	int WALK = 1;
	int PUNCH = 2;
	int KICK = 3;
	int JUMP = 4;
	int SPEED = 5;
	int FALL = 6;
	int HADWOKEN = 9;
	int GRAVITY = 2;
	int MAX_ENEMIES = 500;
	int MAX_HEALTH = 350;
}
